sonar.host.url=https://sonarcloud.io

sonar.sources=system-1-Web/src,system-2-Web/src
sonar.tests=system-1-Web/tests,system-2-Web/tests
sonar.javascript.lcov.reportPaths=system-1-Web/coverage/lcov.info,system-2-Web/coverage/lcov.info
sonar.coverage.exclusions=**/tests/**,**/test/**,**/*.test.*,**/*.spec.*
sonar.exclusions=**/node_modules/**,**/.next/**,**/build/**,**/coverage/**
